### ISSUE TITLE
execution error

### ISSUE THREAD

**Issue by WuChenDi** [zolplay-cn/config-monorepo#1]
Hey ,bro, can you please tell me if this project is available?

I introduced it within the project and executed the command run with the error `pnpm run lint`.

```bash
> next lint

Plugin "react-hooks" was conflicted between ".eslintrc.js » @zolplay/eslint-config » @zolplay/eslint-config-next » eslint-config-next » plugin:react-hooks/recommended" and ".eslintrc.js » @zolplay/eslint-config » @zolplay/eslint-config-next » @zolplay/eslint-config-react » plugin:react-hooks/recommended".
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by thecuvii** [comment]
Thank you for the feedback, and I apologize for the late response. Yes, this project is active and has been used in our projects.

The problem you mentioned above did exist, but it appears to have been fixed.

Would you mind updating `@zolplay/eslint-config` to the latest version and checking if the issue has been resolved?

![CleanShot 2023-09-06 at 11 17 05@2x](https://github.com/zolplay-cn/config-monorepo/assets/11806619/bb40bb6e-6c07-4cdf-9232-278ed9c96780)
![CleanShot 2023-09-06 at 11 16 55@2x](https://github.com/zolplay-cn/config-monorepo/assets/11806619/86607a2c-cf84-428c-80f9-ab97eb175054)

**Comment by WuChenDi** [comment]
Thanks, I updated to the latest version and everything works fine!
